# Generated by Django 4.1.2 on 2023-02-06 16:53

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/default_profile/default.PNG', upload_to=users.utils.rename_imagefile_to_uuid),
        ),
    ]
