# Generated by Django 4.1.2 on 2023-02-02 21:08

import chats.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=15)),
                ('is_open', models.BooleanField(default=False)),
                ('server_profile', models.ImageField(blank=True, default='chats/default.PNG', null=True, upload_to=chats.utils.rename_serverimagefile_to_uuid)),
                ('chat_room', models.ManyToManyField(blank=True, related_name='server_chat_room', to='chats.chatroom')),
                ('user', models.ManyToManyField(blank=True, related_name='server_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, upload_to=chats.utils.rename_chatimagefile_to_uuid)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages_chatroom', to='chats.chatroom')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
