# Generated by Django 4.1.2 on 2023-02-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
